name: Deploy Supabase Edge Functions

on:
  workflow_dispatch:
  push:
    paths:
      - 'supabase/functions/**'
      - '.github/workflows/deploy-edge-functions.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Verify secrets
        run: |
          if [ -z "$SUPABASE_ACCESS_TOKEN" ]; then echo "Missing SUPABASE_ACCESS_TOKEN secret" && exit 1; fi
          if [ -z "$SUPABASE_PROJECT_REF" ]; then echo "Missing SUPABASE_PROJECT_REF secret" && exit 1; fi
          supabase --version

      - name: Deploy process-avatar function
        working-directory: ./
        run: |
          supabase functions deploy process-avatar --project-ref "$SUPABASE_PROJECT_REF"

      - name: Deploy queue-video function
        working-directory: ./
        run: |
          supabase functions deploy queue-video --project-ref "$SUPABASE_PROJECT_REF" 